version: "3.7"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    init: true
    restart: unless-stopped
    user: ${UID}:${GID}
    volumes:
      - ${FILE_BROWSER_DATA_FOLDER}:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
